version: '3.8'

services:
  postgis:
    image: postgis/postgis
    container_name: ipums_postgis_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrea
      POSTGRES_DB: ipums
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgis_data: